TRAINING_DATA = [
    # Fall / danger
    ("The elderly person fell to the ground and is lying motionless.", 1),
    ("The person slipped on the wet floor and collapsed.", 1),
    ("They lost balance and tumbled down the stairs.", 1),
    ("The patient fell from the bed and is unable to get up.", 1),
    ("The person tripped over an obstacle and hit the ground hard.", 1),
    ("Found lying on the floor in an unnatural position, not moving.", 1),
    ("The elderly person went down suddenly and cannot stand.", 1),
    ("Collapsed near the bathroom door, appears unconscious.", 1),
    ("The person crumpled to the floor without warning.", 1),
    ("Detected a sudden drop in posture, person is now on the ground.", 1),
    ("The individual stumbled and crashed into the wall before falling.", 1),
    ("Person appears to have lost consciousness and is on the floor.", 1),
    ("The person is lying face down on the tile floor, no movement detected.", 1),
    ("Sudden fall detected, the person is struggling to get up.", 1),
    ("The elderly person toppled over while trying to stand from the chair.", 1),
    ("Person buckled at the knees and dropped to the floor.", 1),
    ("The resident was found sprawled on the hallway floor.", 1),
    ("The person has been on the ground for several minutes without moving.", 1),
    ("Appears to have fainted, body is limp on the floor.", 1),
    ("The person missed a step and rolled down the staircase.", 1),

    # Caution / unstable
    ("The person is walking very unsteadily and grabbing the wall.", 1),
    ("Wobbling significantly while standing, looks about to fall.", 1),
    ("The elderly person is swaying and struggling to maintain balance.", 1),
    ("Legs appear weak, the person is having difficulty walking.", 1),
    ("The person is leaning heavily on furniture for support.", 1),
    ("Noticed unsteady gait, the person nearly fell twice.", 1),
    ("Head dropped forward in the chair, not responding to sounds.", 1),
    ("No movement detected for over 20 minutes, person appears unresponsive.", 1),
    ("The person has not changed position in a very long time.", 1),
    ("Sitting motionless with eyes closed, no reaction to surroundings.", 1),

    # Normal
    ("The person is sitting comfortably on the sofa watching television.", 0),
    ("Eating a meal at the dining table with normal posture.", 0),
    ("Walking steadily through the hallway at a normal pace.", 0),
    ("The elderly person is sleeping peacefully in bed.", 0),
    ("Doing light stretching exercises in the living room.", 0),
    ("Reading a book while seated in an armchair.", 0),
    ("Standing in the kitchen preparing a cup of tea.", 0),
    ("The person is talking on the phone while sitting.", 0),
    ("Lying in bed under covers, regular breathing visible.", 0),
    ("Calmly resting on the recliner with eyes closed, appears to be napping.", 0),
    ("The person got up from the chair and walked to the kitchen.", 0),
    ("Watering plants on the balcony, moving normally.", 0),
    ("Folding laundry on the bed, coordinated movements.", 0),
    ("Sitting at the desk writing something.", 0),
    ("Watching TV and occasionally changing channels with the remote.", 0),
    ("The person stood up slowly from the sofa and stretched.", 0),
    ("Drinking water while standing by the counter.", 0),
    ("Petting the cat while seated on the couch.", 0),
    ("Cleaning the table with a cloth, normal activity.", 0),
    ("The elderly person is having a conversation with a visitor.", 0),

    # Normal but easy to confuse with a fall
    ("The person slowly laid down on the sofa to rest.", 0),
    ("Carefully sat down on the floor to do yoga stretches.", 0),
    ("Bent down to pick up something from the floor, then stood back up.", 0),
    ("Lowered themselves onto the bed for an afternoon nap.", 0),
    ("Kneeled down to tie their shoelaces.", 0),
    ("Got down on the floor to play with a pet.", 0),
    ("Leaned against the wall briefly to adjust their slipper.", 0),
    ("Sat down on the floor cushion to meditate.", 0),
    ("The person grabbed a cane to avoid falling and continued walking safely.", 0),
    ("Almost lost balance but caught the railing and recovered.", 0),
]
